[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/auth/microsoft/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true